"""initial_users_and_settings

Revision ID: 6f0d9986606a
Revises: 
Create Date: 2026-05-03 21:44:02.223903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f0d9986606a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('target_work_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_locations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('github_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_completed_onboarding', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('profile_completeness', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(), server_default=sa.text("'gemini'"), nullable=False),
    sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('llm_base_url', sa.String(), nullable=True),
    sa.Column('preferred_model', sa.String(), server_default=sa.text("'gemini-2.0-flash'"), nullable=False),
    sa.Column('use_platform_api_key', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('smtp_server', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), server_default=sa.text('587'), nullable=False),
    sa.Column('smtp_username', sa.String(), nullable=True),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=True),
    sa.Column('gmail_access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('gmail_refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('use_gmail_for_send', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_inbox_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_apply_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_apply_daily_limit', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('auto_submit_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cold_mail_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cold_mail_daily_limit', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('match_threshold', sa.Float(), server_default=sa.text('0.65'), nullable=False),
    sa.Column('scrape_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('follow_up_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
